FROM python:3.10-slim

# Install system deps for OpenCV
RUN apt-get update && apt-get install -y ffmpeg libglib2.0-0 libsm6 libxrender1 libxext6 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# copy code
COPY . /app

CMD ["python", "app.py"]
